name: Flake Update

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Flake Update
      run: nix flake update

    - name: Manual Flake check
      run: nix flake check

    - name: Nix Flake Checker
    # You may pin to the exact commit or the version.
    # uses: DeterminateSystems/flake-checker-action@4b90f9fc724969ff153fe1803460917c84fe00a3
      uses: DeterminateSystems/flake-checker-action@v5

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto lint/format

  

