name: Flake Check

on: 
  workflow_run:
    workflows: ["Flake Update"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with: 
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Install Nix Linting and Formatting Tools
      run: nix-env -i statix nixpkgs-fmt -f '<nixpkgs>'
 
    - name: Run Statix Lint
      run: statix fix

    - name: Run Nix Format
      run: nixpkgs-fmt .

    - name: Flake Check
      run: nix flake check
